# Generated by Django 3.2 on 2023-04-14 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_image', models.ImageField(upload_to='images')),
                ('date_release', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
